#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 157.240.11.35
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "157.240.11.35		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
